version: "3"
services:
  jupyterlab:
    platform: "linux/amd64"
    image: csanry/aml:latest
    volumes:
      - ./:/src/
    ports:
      - "0.0.0.0:9000:9000"
    command: "/bin/bash -c 'source activate aml && jupyter lab --no-browser --ip=0.0.0.0 --port=9000 --allow-root --notebook-dir=/src/ --NotebookApp.token=\"\"'"
